import "@repo/ui/globals.css";
import type { Metadata } from "next";

import SessionProvider from "~/providers/SessionProvider";
import { Toaster } from "@repo/ui/components/ui/sonner";

export const metadata: Metadata = {
  title: "Docs",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <SessionProvider>
        <body className={"min-h-screen bg-background font-sans antialiased"}>
          <main>{children}</main>
          <Toaster richColors duration={50000} />
        </body>
      </SessionProvider>
    </html>
  );
}
